export const JAT_GOTRAS = [
  { value: 'Ahlawat', en: 'Ahlawat', hi: 'अहलावत' },
  { value: 'Atwal', en: 'Atwal / Athwal', hi: 'अटवाल / अथवाल' },
  { value: 'Aulakh', en: 'Aulakh', hi: 'औलख' },
  { value: 'Aujla', en: 'Aujla', hi: 'औजला' },
  { value: 'Antil', en: 'Antil / Antal', hi: 'अंतिल / अंतल' },
  { value: 'Awana', en: 'Awana', hi: 'अवाना' },
  { value: 'Aura', en: 'Aura', hi: 'औरा' },
  { value: 'Bajwa', en: 'Bajwa', hi: 'बाजवा' },
  { value: 'Balyan', en: 'Bal / Balyan', hi: 'बल / बल्यान' },
  { value: 'Bains', en: 'Bains', hi: 'बैन्स' },
  { value: 'Bana', en: 'Bana', hi: 'बाणा' },
  { value: 'Banger', en: 'Banger', hi: 'बांगर' },
  { value: 'Beniwal', en: 'Beniwal', hi: 'बेनीवाल' },
  { value: 'Bhadu', en: 'Bhadu', hi: 'भाड़ू' },
  { value: 'Bhakar', en: 'Bhakar / Bhukar', hi: 'भाकर / भुकर' },
  { value: 'Bhambhu', en: 'Bhambhu', hi: 'भांभू' },
  { value: 'Bhangu', en: 'Bhangu', hi: 'भांगू' },
  { value: 'Bhatti', en: 'Bhatti (Jat line)', hi: 'भट्टी (जाट शाखा)' },
  { value: 'Bhullar', en: 'Bhullar', hi: 'भुल्लर' },
  { value: 'Boora', en: 'Boora / Bura', hi: 'बूरा / बुरा' },
  { value: 'Brar', en: 'Brar', hi: 'ब्रार' },
  { value: 'Burdak', en: 'Burdak', hi: 'बुर्दक' },
  { value: 'Chahar', en: 'Chahar', hi: 'चाहर' },
  { value: 'Chahal', en: 'Chahal', hi: 'चहल' },
  { value: 'Chatha', en: 'Chatha', hi: 'चठा' },
  { value: 'Chauhan', en: 'Chauhan (Jat)', hi: 'चौहान (जाट)' },
  { value: 'Cheema', en: 'Cheema', hi: 'चीमा' },
  { value: 'Chhokar', en: 'Chhokar', hi: 'छोकर' },
  { value: 'Chhina', en: 'Chhina', hi: 'छीना' },
  { value: 'Choudhary', en: 'Choudhary (clan)', hi: 'चौधरी (कुल)' },
  { value: 'Dahiya', en: 'Dahiya', hi: 'दहिया' },
  { value: 'Dabas', en: 'Dabas', hi: 'दाबस' },
  { value: 'Dalal', en: 'Dalal', hi: 'दलाल' },
  { value: 'Dagar', en: 'Dagar', hi: 'डागर' },
  { value: 'Deshwal', en: 'Deshwal', hi: 'देशवाल' },
  { value: 'Dhillon', en: 'Dhillon', hi: 'ढिल्लों' },
  { value: 'Dhindsa', en: 'Dhindsa', hi: 'धिंसा' },
  { value: 'Dudi', en: 'Dudi', hi: 'डूडी' },
  { value: 'Duhan', en: 'Duhan', hi: 'दुहान' },
  { value: 'Gahlot', en: 'Gahlot (Jat branch)', hi: 'गहलोत (जाट शाखा)' },
  { value: 'Gathwala', en: 'Gathwala (Malik group)', hi: 'गठवाला (मलिक समूह)' },
  { value: 'Ghanghas', en: 'Ghanghas', hi: 'घंघास' },
  { value: 'Gill', en: 'Gill', hi: 'गिल' },
  { value: 'Godara', en: 'Godara / Godha', hi: 'गोड़ारा / गोधा' },
  { value: 'Gulia', en: 'Gulia', hi: 'गुलिया' },
  { value: 'Goyat', en: 'Goyat', hi: 'गोयत' },
  { value: 'Grewal', en: 'Grewal', hi: 'ग्रेवाल' },
  { value: 'Goraya', en: 'Goraya', hi: 'गोराया' },
  { value: 'Hooda', en: 'Hooda / Huda', hi: 'हुड्डा / हुडा' },
  { value: 'Harsana', en: 'Harsana', hi: 'हर्साना' },
  { value: 'Hingonia', en: 'Hingonia', hi: 'हिंगोनिया' },
  { value: 'Jakhar', en: 'Jakhar', hi: 'जाखड़' },
  { value: 'Jakhad', en: 'Jakhad', hi: 'जाखड़' },
  { value: 'Johiya', en: 'Johiya / Johi (Rajasthan)', hi: 'जोहिया / जोही (राजस्थान)' },
  { value: 'Joon', en: 'Joon', hi: 'जून' },
  { value: 'Kadian', en: 'Kadian / Kadyan', hi: 'कादियान / काड्यान' },
  { value: 'Kaler', en: 'Kaler', hi: 'कलेर' },
  { value: 'Kaliraman', en: 'Kaliraman', hi: 'कलिरामन' },
  { value: 'Kandhal', en: 'Kandhal', hi: 'कांधल' },
  { value: 'Kang', en: 'Kang', hi: 'कांग' },
  { value: 'Kaswan', en: 'Kaswan / Kasvan', hi: 'कस्वान / कासवान' },
  { value: 'Kharb', en: 'Kharb', hi: 'खरब' },
  { value: 'Khichar', en: 'Khichar', hi: 'खीचर' },
  { value: 'Khokhar', en: 'Khokhar (India)', hi: 'खोखर (भारत)' },
  { value: 'Kundu', en: 'Kundu', hi: 'कुंडू' },
  { value: 'Lamba', en: 'Lamba', hi: 'लांबा' },
  { value: 'Lakhlan', en: 'Lakhlan', hi: 'लखलान' },
  { value: 'Lakra', en: 'Lakra', hi: 'लाकड़ा' },
  { value: 'Lohchab', en: 'Lohchab / Lochab', hi: 'लोहचब / लोचब' },
  { value: 'Malik', en: 'Malik', hi: 'मलिक' },
  { value: 'Mann', en: 'Mann / Maan', hi: 'मान / मान' },
  { value: 'Mehla', en: 'Mehla', hi: 'मेहला' },
  { value: 'Mor', en: 'Mor / Morwal', hi: 'मोर / मोरवाल' },
  { value: 'Mirdha', en: 'Mirdha', hi: 'मिर्धा' },
  { value: 'Mavi', en: 'Mavi', hi: 'मावी' },
  { value: 'Nain', en: 'Nain', hi: 'नैन' },
  { value: 'Nandal', en: 'Nandal', hi: 'नांदल' },
  { value: 'Nara', en: 'Nara', hi: 'नारा' },
  { value: 'Narwal', en: 'Narwal / Nirwal', hi: 'नरवाल / निरवाल' },
  { value: 'Pannu', en: 'Pannu', hi: 'पन्नू' },
  { value: 'Pawar', en: 'Pawar / Parmar (Jat)', hi: 'पवार / परमार (जाट)' },
  { value: 'Poonia', en: 'Poonia / Puniya', hi: 'पूनिया / पुनिया' },
  { value: 'Pilania', en: 'Pilania', hi: 'पिलानिया' },
  { value: 'Phogat', en: 'Phogat', hi: 'फोगाट' },
  { value: 'Pahal', en: 'Pahal', hi: 'पाहल' },
  { value: 'Rahar', en: 'Rahar', hi: 'राहर' },
  { value: 'Rangi', en: 'Rangi', hi: 'रांगी' },
  { value: 'Rathi', en: 'Rathi', hi: 'राठी' },
  { value: 'Riar', en: 'Riar', hi: 'रियार' },
  { value: 'Rawat', en: 'Rawat (Jat)', hi: 'रावत (जाट)' },
  { value: 'Sangwan', en: 'Sangwan / Sagwan', hi: 'सांगवान / सगवान' },
  { value: 'Saran', en: 'Saran / Saharan', hi: 'सरन / सहारन' },
  { value: 'Saroha', en: 'Saroha', hi: 'सरोहा' },
  { value: 'Sehrawat', en: 'Sehrawat', hi: 'सेहरावत' },
  { value: 'Sekhon', en: 'Sekhon', hi: 'सेखों' },
  { value: 'Sidhu', en: 'Sidhu', hi: 'सिधू' },
  { value: 'Sihag', en: 'Sihag', hi: 'सिहाग' },
  { value: 'Sindhu', en: 'Sindhu', hi: 'सिंधु' },
  { value: 'Sheoran', en: 'Sheoran / Siwach', hi: 'शेरेान / सिवाच' },
  { value: 'Solanki', en: 'Solanki (Jat)', hi: 'सोलंकी (जाट)' },
  { value: 'Sohu', en: 'Sohu', hi: 'सोहू' },
  { value: 'Sandhu', en: 'Sandhu', hi: 'संधू' },
  { value: 'Tanwar', en: 'Tanwar / Tomar (Jat)', hi: 'तनवार / तोमर (जाट)' },
  { value: 'Tiwana', en: 'Tiwana', hi: 'तिवाना' },
  { value: 'Toor', en: 'Toor', hi: 'तूर' },
  { value: 'Tokas', en: 'Tokas', hi: 'तोकस' },
  { value: 'Thakran', en: 'Thakran', hi: 'ठाकरन' },
  { value: 'Virk', en: 'Virk', hi: 'विर्क' },
  { value: 'Waraich', en: 'Waraich / Varraich', hi: 'वरैच / वर्रैच' },
  { value: '__custom', en: 'Other (type manually)', hi: 'अन्य (स्वयं लिखें)' }
]

export function asOptions(lang = 'en') {
  return JAT_GOTRAS.map((g) => ({
    value: g.value,
    label: lang === 'hi' ? g.hi : g.en,
  }))
}
