// src/constants/hindi-geo.js
// Hindi labels for Indian states/UTs keyed by ISO code from country-state-city.
export const STATE_HI = {
  AN: 'अंडमान और निकोबार द्वीपसमूह',
  AP: 'आंध्र प्रदेश',
  AR: 'अरुणाचल प्रदेश',
  AS: 'असम',
  BR: 'बिहार',
  CH: 'चंडीगढ़',
  CT: 'छत्तीसगढ़',
  DN: 'दादरा और नगर हवेली',
  DD: 'दमन और दीव',
  DH: 'दादरा एवं नगर हवेली और दमन एवं दीव', // some libs use DH (merged UT)
  DL: 'दिल्ली',
  GA: 'गोवा',
  GJ: 'गुजरात',
  HR: 'हरियाणा',
  HP: 'हिमाचल प्रदेश',
  JH: 'झारखंड',
  JK: 'जम्मू और कश्मीर',
  KA: 'कर्नाटक',
  KL: 'केरल',
  LA: 'लद्दाख',
  LD: 'लक्षद्वीप',
  MP: 'मध्य प्रदेश',
  MH: 'महाराष्ट्र',
  MN: 'मणिपुर',
  ML: 'मेघालय',
  MZ: 'मिज़ोरम',
  NL: 'नगालैंड',
  OR: 'ओड़िशा',
  OD: 'ओड़िशा',
  PB: 'पंजाब',
  PY: 'पुदुच्चेरी',
  RJ: 'राजस्थान',
  SK: 'सिक्किम',
  TN: 'तमिलनाडु',
  TG: 'तेलंगाना',
  TS: 'तेलंगाना',
  TR: 'त्रिपुरा',
  UP: 'उत्तर प्रदेश',
  UT: 'उत्तराखंड',
  UK: 'उत्तराखंड',
  WB: 'पश्चिम बंगाल',
};

// Optional: common city Hindi names (fallback to English if not present).
export const CITY_HI = {
  // Jharkhand (examples from your screenshots)
  Ranchi: 'रांची',
  Palamu: 'पालामू',
  Deoghar: 'देवघर',
  Hazaribagh: 'हज़ारीबाग',
  Dumka: 'दुमका',
  Dhanbad: 'धनबाद',
  Bokaro: 'बोकारो',
  Giridih: 'गिरिडीह',
  Simdega: 'सिमडेगा',
  Godda: 'गोड्डा',
  Koderma: 'कोडरमा',
  Latehar: 'लातेहार',

  // A few other common examples (add more anytime)
  Mumbai: 'मुंबई',
  Pune: 'पुणे',
  Delhi: 'दिल्ली',
  Bengaluru: 'बेंगलुरु',
  Kolkata: 'कोलकाता',
  Chennai: 'चेन्नई',
  Jaipur: 'जयपुर',
  Lucknow: 'लखनऊ',
  Patna: 'पटना',
  Goa: 'गोवा',
};
